Scripts/database-ga3/GA2/GA2/urls.py
from django.contrib import admin
from django.urls import path, include
from startpage.views import registerCourier, registerCustomer, registerStaff, login, logout
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('startpage.urls')),
    path('registerCourier/', registerCourier, name="registerCourier"),
    path('registerCustomer/', registerCustomer, name="registerCustomer"),
    path('registerStaff/', registerStaff, name="registerStaff"),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

Scripts/database-ga3/GA2/startpage/urls.py
from django.urls import path
from .views import itemForm,readItem,deleteLaundryList,updateLaundryList,laundryListForm,readLaundryList, topUp, topUpForm, home, deleteTopup, updateTopup, readService, readTestimony, deleteTestimony, testimonyForm, statusRead, updateTestimony, updateService

app_name = "startpage"


urlpatterns = [
    path('', home, name="home"),
    path('topup/', topUp, name="topup"),
    path('topupForm/', topUpForm, name="topUpForm"),
    path('deleteTopup/<email>/<date>/', deleteTopup, name="delete_topUp"),
    path('updateTopup/<email>/<date>/', updateTopup, name="update_topUp"),
    path('testimony/', readTestimony, name="testimony"),
    path('testimonyForm/', testimonyForm, name="testimonyForm"),
    path('deleteTestimony/<email>/<date>/', deleteTestimony, name="delete_testimony"),
    path('updateTestimony/<email>/<date>/', updateTestimony, name="update_testimony"),
    path('service/', readService, name="service"),
    path('status/', statusRead, name="status"),
    path('updateService/<code>/', updateService, name="update_service"),
    path('laundryList/', readLaundryList, name="laundryList"),
    path('laundryListForm/', laundryListForm, name="laundryListForm"),
    path('updateLaundryList/<email>/<date>/', updateLaundryList, name="updateLaundryList"),
    path('deleteLaundryList/<email>/<date>/', deleteLaundryList, name="deleteLaundryList"),
    path('item/', readItem, name="item"),
    path('item_user/', readItem, name="item2"),
    path('itemForm/', itemForm, name="itemForm"),
]

Scripts/database-ga3/GA2/startpage/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone

# Create your models here.
class DpayTopUpTransaction(models.Model):
    email = models.EmailField()
    nominal = models.FloatField()
    date = models.DateField(default=timezone.now())

    def __str__(self):
        return str(self.email)


class Status(models.Model):
    code = models.CharField(max_length = 10)
    name = models.CharField(max_length = 15)
    
    def __str__(self):
        return str(self.code)


    def __str__(self):
        return str(self.name)

class Testimony(models.Model):
    email = models.EmailField()
    transaction_date = models.DateField(default=datetime.today())
    status = models.TextField()
    rating = models.IntegerField()

    def __str__(self):
        return str(self.email)

class Service(models.Model):
    code = models.CharField(max_length= 10)
    name = models.CharField(max_length = 50)
    duration = models.CharField(max_length = 10)
    price = models.DecimalField(decimal_places = 2, max_digits = 9)

    def __str__(self):
        return str(self.code)

class LaundryList(models.Model):
    email = models.EmailField()
    date = models.DateField(default=datetime.today())
    serialno = models.IntegerField()
    amount = models.IntegerField()
    itemtype = models.CharField(max_length = 10)

    def __str__(self):
        return str(self.email)

class Item(models.Model):
    code = models.IntegerField()
    name = models.CharField(max_length = 10)

    def __str__(self):
        return str(self.code)

Scripts/database-ga3/GA2/startpage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .models import DpayTopUpTransaction, Service, Testimony, Status,LaundryList,Item
from .forms import *
from datetime import datetime
from django.core.paginator import  Paginator
from django.db import connection,  IntegrityError, transaction
from collections import namedtuple
from django.forms import formset_factory
from django.contrib import messages

# Create your views here.
def registerStaff(request):
    if request.method == "POST":
        form = StaffForm(request.POST)
        print(request.POST)
    else:
        form = StaffForm()
    return render(request, 'startpage/registerUser.html', {'form':form})

def registerCustomer(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        print(request.POST)
    else:
        form = CustomerForm()
    return render(request, 'startpage/registerUser.html', {'form':form})

def registerCourier(request):
    if request.method == "POST":
        form = CourierForm(request.POST)
        print(request.POST)
    else:
        form = CourierForm()
    return render(request, 'startpage/registerUser.html', {'form':form})

def login(request):
    login_form = loginForm(request.POST)
    if request.method == "POST" and login_form.is_valid():
        email = login_form.cleaned_data['email']
        raw_password = login_form.cleaned_data['password']
    
        with connection.cursor() as cursor:
            cursor.execute('SELECT password FROM SILAU.USER WHERE email = %(email)s', {'email': email})
            existing_user_password = cursor.fetchone()
            if (existing_user_password is not None) and (existing_user_password == raw_password) :
                cursor.execute('SELECT email FROM Customer WHERE email = %(email)s', {'email': email})
                customer_user = cursor.fetchone()
                if customer_user is not None:
                    request.session['user'] = 'customer'

                cursor.execute('SELECT email FROM STAFF WHERE email = %(email)s', {'email': email})
                staff_user = cursor.fetchone()
                if staff_user is not None:
                    request.session['user'] = 'staff'

                cursor.execute('SELECT email FROM COURIER WHERE email = %(email)s', {'email': email})
                courier_user = cursor.fetchone()
                if courier_user is not None:
                    request.session['user'] = 'courier'

                request.session['email'] = email	
                return redirect('startpage:home')
            else:
                messages.error(request, f'Invalid Password')
                return redirect('login')
                pass
    return render(request, 'startpage/login.html', {"login_form": loginForm()})

def logout(request):
	request.session.flush()
	return redirect('startpage:home')

def home(request):
    try:
        print(request.session['user'])
        print(request.session['email'])
        message = "You are logged in as a " + request.session['user']
    except:
        print('You Are Logged Out')
        message = 'You Are Logged Out'

    context = {'message' : message}
    return render(request, 'startpage/home.html', context)

def topUp(request):
    with connection.cursor() as cursor :
        cursor.execute("SELECT * FROM DPAY_TOPUP_TRANSACTION")
        columns = [col[0] for col in cursor.description]
        data = [dict(zip(columns,row)) for row in cursor.fetchall()]
        context = {'data' : data}
    return render(request, 'topUp/topupRead.html', context)

def topUpForm(request):
    if request.method == "POST":
        form = TopUp_Input(request.POST)
        if (form.is_valid()):
            form.save()
            return redirect('startpage:topup')
    form = TopUp_Input()
    return render(request, 'topUp/topUpForm.html', {'form':form})

def deleteTopup(request, email, date):
    object = DpayTopUpTransaction.objects.get(email=email, date=date)
    object.delete()
    return render(request, 'topUp/topupRead.html')

def updateTopup(request, email, date):
    object = DpayTopUpTransaction.objects.get(email=email, date=date)
    response = {'object' : object}
    form = TopUp_Update(request.POST, instance=object)
    if (form.is_valid()):
            form.save()
            return redirect('startpage:topup')
    form = TopUp_Update()
    return render(request, 'topUp/topUpUpdate.html', {'form':form, 'object':object})

def testimonyForm(request):
    if request.method == "POST":
        print(request.POST)
        # form = TestimonyForm(request.POST)
        # if (form.is_valid()):
        #     form.save()
    form = TestimonyForm()
    return render(request, 'testimony/testimonyForm.html', {'form':form})

def deleteTestimony(request, email, date):
    object = Testimony.objects.get(email=email, transaction_date=date)
    object.delete()
    return render(request, 'testimony/testimonyRead.html')

def updateTestimony(request, email, date):
    # object = Testimony.objects.get(email=email, transaction_date=date)
    # response = {'object' : object}
    # form = Testimony_Update(request.POST, instance=object)
    # if (form.is_valid()):
    #         form.save()
    #         return redirect('startpage:testimony')
    if request.method == 'POST':
        print(request.POST)
        # form = Testimony_Update(request.POST)
        # if (form.is_valid()):
        #     # form.save()
        #     try:
        #         with connection.cursor() as cursor:
        #             with transaction.atomic():
        #                 cursor.execute("""\
        #                 UPDATE TESTIMONY SET status = %s, rating = %s
        #                 WHERE email=%s AND transaction=%s""", [request.])
        #     except IntegrityError:
        #         pass
        return redirect('startpage:testimony')
    else:
        with connection.cursor() as cursor:
            cursor.execute("SELECT email, transaction_date FROM TESTIMONY where email=%s AND transaction_date=%s LIMIT 1;", [email, date] )
            data = cursor.fetchone()
            if data is None:
                return redirect('apotek/')
            columns = [col[0] for col in cursor.description]
            old_data = dict(zip(columns, data))
            form = Testimony_Update(initial = old_data)
        return render(request, 'testimony/testimonyUpdate.html', {'form':form, 'old_data': old_data})

def readTestimony(request):
    # testimony_data = Testimony.objects.all()
    
    # paginator = Paginator(testimony_data, 3)
    # page = request.GET.get('page')
    # testimony_data = paginator.get_page(page)

    with connection.cursor() as cursor :
        cursor.execute("SELECT * FROM TESTIMONY")
        columns = [col[0] for col in cursor.description]
        data = [dict(zip(columns,row)) for row in cursor.fetchall()]
        context = {'data' : data}
    # response = {'testimony_data' : testimony_data}
    return render(request, 'testimony/testimonyRead.html', context)



def readService(request):
    # service_data = Service.objects.all()

    # paginator = Paginator(service_data, 3)
    # page = request.GET.get('page')
    # service_data = paginator.get_page(page)

    with connection.cursor() as cursor :
        cursor.execute("SELECT * FROM SERVICE")
        columns = [col[0] for col in cursor.description]
        data = [dict(zip(columns,row)) for row in cursor.fetchall()]
        context = {'data' : data}

    # response = {'service_data' : service_data}
    return render(request, 'service/serviceRead.html', context)

def updateService(request, code):
    # object = Service.objects.get(code = code)
    # response = {'object' : object}
    # form = Service_Update(request.POST, instance=object)
    # if (form.is_valid()):
    #         form.save()
    #         return redirect('startpage:service')
    if request.method == 'POST':
        form = ServiceForm(request.POST)
        if form.is_valid():
            cleaned = form.cleaned_data
            try:
                with connection.cursor() as cursor:
                    with transaction.atomic():
                        cursor.execute("""\
                        UPDATE Service SET name = %s, duration = %s, price = %s 
                        WHERE code=%s""",
                                    [cleaned.get("name"), cleaned.get("duration"),
                                    cleaned.get('price'), cleaned.get('code')])
            except IntegrityError:
                pass
            return redirect('startpage:service')
    else:
        form = ServiceForm(initial={'code':code})
    return render(request, 'service/serviceUpdate.html', {'form':form})

def statusRead(request):
    # status_data = Status.objects.all()
    # response = {'status_data' : status_data}
    with connection.cursor() as cursor :
        cursor.execute("SELECT * FROM STATUS")
        columns = [col[0] for col in cursor.description]
        data = [dict(zip(columns,row)) for row in cursor.fetchall()]
        context = {'data' : data}
    return render(request, 'status/status.html', context)


def updateLaundryList(request, email, date):
    object = LaundryList.objects.get(email = email,date=date)
    response = {'object' : object}
    form = LaundryList_Update(request.POST, instance=object)
    if (form.is_valid()):
            form.save()
            return redirect('startpage:laundryList')
    form = LaundryList_Update()
    return render(request, 'laundryList/laundryListUpdate.html', {'form':form, 'object':object})

def deleteLaundryList(request, email, date):
    object = LaundryList.objects.get(email = email,date=date)
    object.delete()
    return render(request, 'laundryList/laundryListRead.html')

def readLaundryList(request):
    with connection.cursor() as cursor :
        cursor.execute("SELECT * FROM LAUNDRY_LIST")
        columns = [col[0] for col in cursor.description]

Scripts/database-ga3/GA2/startpage/templates/startpage/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/carousel/">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <style>
      body {
        padding : 3rem;
    }

      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }
  
      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }


    .pagination {
        text-align: center;
        margin-top: 1em;
    }

    .pagination-action {
        margin: 0 0.1em;
        display: inline-block;
        padding: 0.5em;
        color: #bb99bb;
        font-size: 1.3em;
    }

    .pagination-action:hover{
        color : #3354AA
    }
    </style>

  </head>

  <body>
    <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
              <a class="navbar-brand" href="#">GA2 BASDUT</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'startpage:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'registerCustomer' %}">Register Customer</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'registerCourier' %}">Register Courier</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'registerStaff' %}">Register Staff</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'startpage:topup' %}">Top Up</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'startpage:testimony' %}">Testimony</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'startpage:service' %}">Service</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'startpage:status' %}">Status</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'startpage:laundryList' %}">Laundry List</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'startpage:item' %}">Item</a>
                    </li>
                </ul>
              </div>
            </nav>
          </header>
    <main role="main">

    {% block content %} {% endblock %}
  
    </main>
  </body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</html>

Scripts/database-ga3/GA2/startpage/templates/startpage/home.html
{% extends "startpage/base.html" %}
{% load static %}

{% block content %}
  <h3>{{message}}</h3>
{% endblock %}

Scripts/database-ga3/GA2/startpage/templates/startpage/login.html
{% extends "startpage/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="content-section">
                <form action="" method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Log In</legend>
                            {{login_form.as_p}}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit" id="login_btn">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Scripts/database-ga3/GA2/startpage/templates/startpage/logout.html
{% extends "startpage/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h2>You have been logged out</h2>    
            <div class="border-top pt-3">
                <small class="text-muted">
                    <a href="{% url 'login' %}">Log In Again</a>
                </small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Scripts/database-ga3/GA2/startpage/templates/startpage/registerUser.html
{% extends "startpage/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="content-section">
                <form action="" method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Join Today<br><br>
                            {{form|crispy}}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit" id="signup_btn">Sign Up</button>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Already Have An Account ? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}